[project]
name = "ed25519brute"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cryptography>=46.0.3",
    "pynacl>=1.6.1",
    "pytest>=9.0.2",
]
